apiVersion: v1
kind: Service
metadata:
  name: ftps-ser
  labels:
    app: ftps-app
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps-app
  ports:
    - port : 20
      name : ftps-data
    - port : 21
      name : ftps-conn
    - port : 21000
      name : ftps-pass

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dep
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
        - name           : ftps
          image          : ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 21000
...
