apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-ser
  labels:
    app: phpmyadmin-app
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: phpmyadmin-app
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-dep
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
        - name           : phpmyadmin
          image          : phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
...
