apiVersion: v1
kind: Service
metadata:
  name: wordpress-ser
  labels:
    app: wordpress-app
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: wordpress-app
  loadBalancerIP: 192.168.99.100
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
  labels:
    app: wordpress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
