apiVersion: v1
kind: Service
metadata:
  name: grafana-ser
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: grafana-app
  ports:
    - port      : 3000
      targetPort: 3000
      protocol  : TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
...
