apiVersion: v1
kind: Service
metadata:
  name: nginx-ser
  labels:
    app: nginx-app
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: nginx-app
  ports:
    - port      : 80
      targetPort: 80
      protocol  : TCP
      name      : http
    - port      : 443
      targetPort: 443
      protocol  : TCP
      name      : https
    - port      : 22
      targetPort: 22
      protocol  : TCP
      name      : ssh

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name           : nginx
          image          : nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
...
